"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ygi)6-96j1+k!q&@36ano(u!56v08b07mt(!y&42uc&96krp_3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #'jazzmin',
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'tr4cking_rest_api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Configuración CSRF
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
# Configuración de cookies
CSRF_COOKIE_SECURE = False  # True en producción con HTTPS
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SECURE = False  # True en producción
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'tr4cking_rest_api' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'tr4cking_db',
        'USER': 'postgres',
        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'  # Cambia 'en-us' por 'es'
TIME_ZONE = 'America/Asuncion'  # Ajusta a tu zona horaria

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'tr4cking_rest_api' / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

UNFOLD = {
    "SITE_TITLE": "Tr4cking",
    "SITE_HEADER": "Tr4cking Admin",
    "SITE_URL": "http://localhost:5173",
    "SITE_ICON": False,
    "THEME": "dark",
    "COLORS": {
        "primary": {
            "50": "250 245 255",
            "100": "243 232 255",
            "200": "233 213 255",
            "300": "216 180 254",
            "400": "192 132 252",
            "500": "168 85 247",
            "600": "147 51 234",
            "700": "126 34 206",
            "800": "107 33 168",
            "900": "88 28 135",
            "950": "59 7 100",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "collapsible": True,
        "navigation": [
            {
                "title": _("Personas"),
                "icon": "user",
                "items": [
                    {
                        "title": _("Personas"),
                        "icon": "person",
                        "link": reverse_lazy("admin:tr4cking_rest_api_persona_changelist"),
                    },
                    {
                        "title": _("Clientes"),
                        "icon": "person",
                        "link": reverse_lazy("admin:tr4cking_rest_api_cliente_changelist"),
                    },
                    {
                        "title": _("Pasajeros"),
                        "icon": "person",
                        "link": reverse_lazy("admin:tr4cking_rest_api_pasajero_changelist"),
                    },
                ],
            },
            {
                "title": _("Empresas"),
                "icon": "building-office",
                "items": [
                    {
                        "title": _("Empresas"),
                        "icon": "business",
                        "link": reverse_lazy("admin:tr4cking_rest_api_empresa_changelist"),
                    },
                    {
                        "title": _("Empleados"),
                        "icon": "people",
                        "link": reverse_lazy("admin:tr4cking_rest_api_empleado_changelist"),
                    },
                ],
            },
            {
                "title": _("Geografía"),
                "icon": "map",
                "items": [
                    {
                        "title": _("Localidades"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:tr4cking_rest_api_localidad_changelist"),
                    },
                    {
                        "title": _("Paradas"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:tr4cking_rest_api_parada_changelist"),
                    },
                ],
            },
            {
                "title": _("Transporte"),
                "icon": "truck",
                "items": [
                    {
                        "title": _("Buses"),
                        "icon": "directions_bus",
                        "link": reverse_lazy("admin:tr4cking_rest_api_bus_changelist"),
                    },
                    {
                        "title": _("Asientos"),
                        "icon": "event_seat",
                        "link": reverse_lazy("admin:tr4cking_rest_api_asiento_changelist"),
                    },
                    {
                        "title": _("Rutas"),
                        "icon": "alt_route",
                        "link": reverse_lazy("admin:tr4cking_rest_api_ruta_changelist"),
                    },
                    {
                        "title": _("Detalles de Rutas"),
                        "icon": "alt_route",
                        "link": reverse_lazy("admin:tr4cking_rest_api_detalleruta_changelist"),
                    },
                ],
            },
            {
                "title": _("Viajes y Servicios"),
                "icon": "calendar_today",
                "items": [
                    {
                        "title": _("Viajes"),
                        "icon": "commute",
                        "link": reverse_lazy("admin:tr4cking_rest_api_viaje_changelist"),
                    },
                    {
                        "title": _("Pasajes"),
                        "icon": "confirmation_number",
                        "link": reverse_lazy("admin:tr4cking_rest_api_pasaje_changelist"),
                    },
                    {
                        "title": _("Reservas"),
                        "icon": "book_online",
                        "link": reverse_lazy("admin:tr4cking_rest_api_reserva_changelist"),
                    },
                    {
                        "title": _("Encomiendas"),
                        "icon": "local_shipping",
                        "link": reverse_lazy("admin:tr4cking_rest_api_encomienda_changelist"),
                    },
                ],
            },
            {
                "title": _("Facturación"),
                "icon": "document-text",
                "items": [
                    {
                        "title": _("Tipos de Documento"),
                        "icon": "description",
                        "link": reverse_lazy("admin:tr4cking_rest_api_tipodocumento_changelist"),
                    },
                    {
                        "title": _("Timbrados"),
                        "icon": "description",
                        "link": reverse_lazy("admin:tr4cking_rest_api_timbrado_changelist"),
                    },
                    {
                        "title": _("Cabeceras de Factura"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:tr4cking_rest_api_cabecerafactura_changelist"),
                    },
                    {
                        "title": _("Detalles de Factura"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:tr4cking_rest_api_detallefactura_changelist"),
                    },
                    {
                        "title": _("Historial de Facturas"),
                        "icon": "history",
                        "link": reverse_lazy("admin:tr4cking_rest_api_historialfactura_changelist"),
                    },
                ],
            },
            {
                "title": _("Caja"),
                "icon": "account_balance_wallet",
                "items": [
                    {
                        "title": _("Cajas"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:tr4cking_rest_api_caja_changelist"),
                    },
                    {
                        "title": _("Cabeceras de Caja"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:tr4cking_rest_api_cabeceracaja_changelist"),
                    },
                    {
                        "title": _("Detalles de Caja"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:tr4cking_rest_api_detallecaja_changelist"),
                    },
                ],
            },
            {
                "title": _("Configuración"),
                "icon": "settings",
                "items": [
                    {
                        "title": _("Usuarios"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Grupos"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
    "ENVIRONMENT": "development",
    "DASHBOARD_CALLBACK": "tr4cking_rest_api.admin_views.dashboard_callback",
}