# Generated by Django 5.1.7 on 2025-05-18 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id_bus', models.BigAutoField(primary_key=True, serialize=False)),
                ('placa', models.TextField(unique=True)),
                ('marca', models.TextField(blank=True, null=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Mantenimiento', 'Mantenimiento'), ('Inactivo', 'Inactivo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('direccion_legal', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('coordenadas', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cedula', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.TextField(help_text='Requerido para facturación')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id_ruta', models.BigAutoField(primary_key=True, serialize=False)),
                ('duracion_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id_asiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_asiento', models.IntegerField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Reservado', 'Reservado'), ('Ocupado', 'Ocupado')], default='Disponible', max_length=20)),
                ('tipo_asiento', models.CharField(blank=True, choices=[('Semi-cama', 'Semi-cama'), ('Cama', 'Cama')], max_length=20, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.bus')),
            ],
            options={
                'unique_together': {('bus', 'numero_asiento')},
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empresa'),
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id_parada', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('coordenadas', models.FloatField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.localidad')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id_pasajero', models.BigAutoField(primary_key=True, serialize=False)),
                ('cedula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('dv', models.CharField(blank=True, help_text='Dígito verificador (opcional)', max_length=2, null=True)),
                ('razon_social', models.CharField(help_text='Para facturación, prioridad: auth_user > cliente o empleado para casuales', max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cedula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.BigAutoField(primary_key=True, serialize=False)),
                ('hora_salida', models.TimeField()),
                ('dias_semana', models.CharField(max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.ruta')),
            ],
            options={
                'unique_together': {('ruta', 'hora_salida')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioPersona',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cedula', models.OneToOneField(db_column='cedula', on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.persona')),
            ],
            options={
                'db_table': 'usuario_persona',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id_viaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.bus')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.horario')),
            ],
            options={
                'unique_together': {('bus', 'fecha', 'horario')},
            },
        ),
        migrations.CreateModel(
            name='Pasaje',
            fields=[
                ('id_pasaje', models.BigAutoField(primary_key=True, serialize=False)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.asiento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cliente')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='Encomienda',
            fields=[
                ('id_encomienda', models.BigAutoField(primary_key=True, serialize=False)),
                ('flete', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remitente', models.CharField(max_length=100)),
                ('ruc_ci', models.CharField(max_length=20)),
                ('numero_contacto', models.CharField(max_length=20)),
                ('tipo_envio', models.CharField(choices=[('sobre', 'Sobre'), ('paquete', 'Paquete'), ('ambos', 'Ambos')], max_length=10)),
                ('cantidad_sobre', models.PositiveIntegerField(default=0)),
                ('cantidad_paquete', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cliente')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino_encomienda', to='tr4cking_rest_api.parada')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_encomienda', to='tr4cking_rest_api.parada')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('parada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.parada')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.ruta')),
            ],
            options={
                'unique_together': {('ruta', 'orden'), ('ruta', 'parada')},
            },
        ),
    ]
