# Generated by Django 5.1.7 on 2025-04-07 19:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('es_principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion_legal', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ciudad', 'Ciudad'), ('pueblo', 'Pueblo'), ('parada', 'Parada Rural')], max_length=20)),
                ('es_terminal', models.BooleanField(default=False)),
                ('coordenadas', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_timbrado', models.CharField(max_length=15, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descripcion', models.TextField()),
                ('requiere_cliente_registrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=15, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'Mantenimiento'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ejecutivo', 'Ejecutivo'), ('semi-cama', 'Semi-cama'), ('cama', 'Cama')], max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.bus')),
            ],
            options={
                'unique_together': {('bus', 'numero_asiento')},
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('ruc', models.CharField(blank=True, max_length=15, null=True)),
                ('dv', models.CharField(blank=True, max_length=2, null=True)),
                ('telefono', models.CharField(max_length=30)),
                ('direccion', models.TextField()),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrado_por_empleado', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
                ('fecha_contratacion', models.DateField()),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.agencia')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CabeceraFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_iva_10', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_iva_5', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('anulada', 'Anulada')], default='emitida', max_length=20)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.agencia')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empleado')),
                ('timbrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.timbrado')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.tipodocumento')),
            ],
        ),
        migrations.AddField(
            model_name='agencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empresa'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='localidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.localidad'),
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('duracion_estimada', models.DurationField()),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_destino', to='tr4cking_rest_api.localidad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_origen', to='tr4cking_rest_api.localidad')),
            ],
            options={
                'unique_together': {('origen', 'destino')},
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pasaje', 'Pasaje'), ('encomienda', 'Encomienda')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('detalles', models.JSONField(default=dict)),
                ('asiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.asiento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.SmallIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(max_length=100)),
                ('iva_porcentaje', models.SmallIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tr4cking_rest_api.cabecerafactura')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_ruta', 'En Ruta'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.ruta')),
            ],
            options={
                'unique_together': {('bus', 'fecha', 'ruta')},
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.viaje'),
        ),
        migrations.AlterUniqueTogether(
            name='agencia',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.CreateModel(
            name='ParadaRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.SmallIntegerField()),
                ('es_principal', models.BooleanField(default=False)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.localidad')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='tr4cking_rest_api.ruta')),
            ],
            options={
                'verbose_name': 'Parada de Ruta',
                'verbose_name_plural': 'Paradas de Ruta',
                'ordering': ['ruta', 'orden'],
                'unique_together': {('ruta', 'orden')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='servicio',
            unique_together={('viaje', 'asiento')},
        ),
    ]
