# Generated by Django 5.1.7 on 2025-05-17 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr4cking_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encomienda',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino_encomienda', to='tr4cking_rest_api.parada'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen_encomienda', to='tr4cking_rest_api.parada'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.horario'),
        ),
    ]
