# Generated by Django 5.1.7 on 2025-05-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr4cking_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('cedula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tr4cking_rest_api.persona')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.empresa')),
            ],
        ),
    ]
