# Generated by Django 5.1.7 on 2025-04-07 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr4cking_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_salida', models.TimeField()),
                ('dias_semana', models.CharField(max_length=7)),
                ('activo', models.BooleanField(default=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tr4cking_rest_api.ruta')),
            ],
            options={
                'unique_together': {('ruta', 'hora_salida')},
            },
        ),
    ]
